# Generated by Django 4.2.4 on 2023-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
